name = "interactive-avatar-nextjs"
compatibility_date = "2024-11-01"

[pages]
# This is where next-on-pages places static assets
build_output_dir = ".vercel/output/static"

# Environment variables for local `wrangler pages dev` can be placed under [vars]
# [vars]
# NEXT_PUBLIC_SOME_FLAG = "true"
