name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test-lint:
    name: Lint, Typecheck, Build, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
          cd components/external/zod-react-form-auto
          pnpm install
          cd ../../..
          pnpm add ./components/external/zod-react-form-auto

      - name: Typecheck
        run: pnpm run typecheck || echo "Typecheck failed but continuing workflow"
        continue-on-error: true

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Typecheck results: ${{ job.status }}"

      - name: Lint (Biome)
        run: pnpm run lint || echo "Lint issues found (non-blocking for now)"
        continue-on-error: true

      - run: pnpm run build
      - run: pnpm run test

      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
        continue-on-error: true

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
  notify-slack:
    needs: build-test-lint
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'general'
          slack-message: "CI ${{ job.status }} for ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}