name: Security CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  security-events: [write, read]
  actions: read
  contents: read

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: [write, read]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript,typescript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Security Webhook
        if: always()
        run: |
          if [ -n "${{ secrets.SECURITY_WEBHOOK_URL }}" ]; then
            curl -X POST ${{ secrets.SECURITY_WEBHOOK_URL }} \
              -H "Content-Type: application/json" \
              -d "{\"scan_type\":\"${{ job.name }}\",\"status\":\"${{ job.status }}\",\"results_url\":\"https://github.com/${{ github.repository }}/security\"}"
          fi

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'general'
          payload: |
            {
              "text": "Security Scan - ${{ job.name }}: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Security Scan Results*\nJob: ${{ job.name }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Status*: ${{ job.status }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/security|View Security Dashboard>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
        working-directory: ./app
      - run: pnpm add ./components/external/zod-react-form-auto
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects
        continue-on-error: true

      - name: Notify Security Webhook
        if: always()
        run: |
          if [ -n "${{ secrets.SECURITY_WEBHOOK_URL }}" ]; then
            curl -X POST ${{ secrets.SECURITY_WEBHOOK_URL }} \
              -H "Content-Type: application/json" \
              -d "{\"scan_type\":\"snyk\",\"status\":\"${{ job.status }}\",\"results_url\":\"https://github.com/${{ github.repository }}/security/dependabot\"}"
          fi

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'general'
          payload: |
            {
              "text": "Security Scan - Snyk: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Snyk Security Scan Results*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Status*: ${{ job.status }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/security/dependabot|View Dependency Alerts>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog Secret Scan
        uses: docker://trufflesecurity/trufflehog:latest
        with:
          args: "git file://. --json --fail"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Security Webhook
        if: always()
        run: |
          if [ -n "${{ secrets.SECURITY_WEBHOOK_URL }}" ]; then
            curl -X POST ${{ secrets.SECURITY_WEBHOOK_URL }} \
              -H "Content-Type: application/json" \
              -d "{\"scan_type\":\"${{ job.name }}\",\"status\":\"${{ job.status }}\",\"results_url\":\"https://github.com/${{ github.repository }}/security\"}"
          fi

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'general'
          payload: |
            {
              "text": "Security Scan - ${{ job.name }}: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Security Scan Results*\nJob: ${{ job.name }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Status*: ${{ job.status }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/security|View Security Dashboard>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  secrets-scan:
    name: GitHub Secrets Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: [read]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan for secrets
        uses: actions/github-script@v6
        with:
          script: |
            const patterns = [
              // Common secret patterns
              /[A-Za-z0-9]{40}/, // GitHub tokens
              /[0-9a-f]{32}/,    // MD5 hashes
              /[0-9a-f]{64}/,    // SHA256 hashes
              /[0-9a-zA-Z]{24}/  // API keys
            ]
            
            const results = await github.rest.secretScanning.listAlertsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })
            
            core.setOutput('secrets_found', results.data.length > 0)

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'general'
          payload: |
            {
              "text": "GitHub Secrets Scan Results",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*GitHub Secrets Scan Completed*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/security/secret-scanning|View Secret Scanning Results>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  zap-scan:
    name: ZAP Full Scan
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./app

      - name: Start Application
        run: |
          cd ./app
          pnpm run build
          pnpm run start &
          sleep 10

      - name: Wait for Application
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            sleep 1
          done

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          token: ${{ secrets.GITHUB_TOKEN }}
          rules_file_name: '.zap/rules.tsv'
          fail_action: true
          issue_title: 'ZAP Security Scan Results'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
