name: Security CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm add ./components/external/zod-react-form-auto
      - run: pnpm run typecheck || echo "Typecheck failed but continuing workflow"
      - uses: slackapi/slack-github-action@v1.25.0
        if: always()
        with:
          channel-id: 'general'
          slack-message: "Typecheck results: ${{ job.status }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,typescript
          queries: security-extended

      # Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  secret-scanning:
    name: GitHub Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog Secret Scan
        uses: docker://trufflesecurity/trufflehog:latest
        with:
          args: "git file://. --json --fail"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
