name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          echo "Testing secrets..."
          echo "SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL != '' && 'SET' || 'MISSING' }}"
          echo "SNYK_TOKEN: ${{ secrets.SNYK_TOKEN != '' && 'SET' || 'MISSING' }}"
          echo "MCP_SERVER_URL: ${{ secrets.MCP_SERVER_URL != '' && 'SET' || 'MISSING' }}"
          echo "MCP_AUTH_TOKEN: ${{ secrets.MCP_AUTH_TOKEN != '' && 'SET' || 'MISSING' }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
